steps:
  - name: node:12
    entrypoint: npm
    args: ["install"]
  - name: node:12
    entrypoint: npm
    args: ["run", "build"]
  - name: "gcr.io/cloud-builders/gcloud"
    args: ["app", "deploy"]
    timeout: "1600s"
    env:
      - "NODE_ENV=${_NODE_ENV}"
